[package]
name = "shape_inference"
version = "0.1.0"
authors = ["Erik Vesteraas <erik@vestera.as>"]

[dependencies]
serde_json = { version = "0.9", features = ["preserve_order"] }
linked-hash-map = { version = "0.4.1" }
